[tool.black]
line-length = 79
include = '''
/(
    src
  | tst
  | artifact
)/
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.nox
  | __pycache__
  | \.pyc$
  | \.ipynb$
  | \.md$
  | build
  | .venv
  | doc
  | log
  | install
  | dist
  | \.eggs
)/
| .*\.xml$
| .*\.txt$
| .*\.tfrecord$
'''

[tool.isort]
profile = "black"
src_paths = [".","src", "tst", "artifact"]
skip=[".tox",".nox",".venv","doc","install","log"]
skip_glob=[".venv/*","doc/*","install/*","log/*"]
line_length = 79
sections="FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_first_party = "src"
