
# This is a basic workflow to help you get started with Actions

name: Python3 Ubuntu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r install/py/requirements.actions.txt
      - name: Precommit check
        run: |
          pre-commit install
          pre-commit run
          pre-commit run --all-files
  
      # Test python scripts
      - name: Test with pytest
        run: |
          pip install python-coveralls
          python -m pytest --cov=./dfp --cov-report term-missing
          pip install coveragepy-lcov
          coveragepy-lcov --data_file_path .coverage --output_file_path lcov.info
      # Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
